"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class gps_msg(object):
    __slots__ = ["time", "lat", "longtd", "altitude", "utm_x", "utm_y"]

    def __init__(self):
        self.time = 0
        self.lat = 0.0
        self.longtd = 0.0
        self.altitude = 0.0
        self.utm_x = 0.0
        self.utm_y = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(gps_msg._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qfffff", self.time, self.lat, self.longtd, self.altitude, self.utm_x, self.utm_y))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != gps_msg._get_packed_fingerprint():
            raise ValueError("Decode error")
        return gps_msg._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = gps_msg()
        self.time, self.lat, self.longtd, self.altitude, self.utm_x, self.utm_y = struct.unpack(">qfffff", buf.read(28))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if gps_msg in parents: return 0
        tmphash = (0xa5cfa4abd7a01e82) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if gps_msg._packed_fingerprint is None:
            gps_msg._packed_fingerprint = struct.pack(">Q", gps_msg._get_hash_recursive([]))
        return gps_msg._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

