/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package gps_lcm;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class gps_msg implements lcm.lcm.LCMEncodable
{
    public long time;
    public float lat;
    public float longtd;
    public float altitude;
    public float utm_x;
    public float utm_y;
 
    public gps_msg()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xa5cfa4abd7a01e82L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(gps_lcm.gps_msg.class))
            return 0L;
 
        classes.add(gps_lcm.gps_msg.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.time); 
 
        outs.writeFloat(this.lat); 
 
        outs.writeFloat(this.longtd); 
 
        outs.writeFloat(this.altitude); 
 
        outs.writeFloat(this.utm_x); 
 
        outs.writeFloat(this.utm_y); 
 
    }
 
    public gps_msg(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public gps_msg(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static gps_lcm.gps_msg _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        gps_lcm.gps_msg o = new gps_lcm.gps_msg();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.time = ins.readLong();
 
        this.lat = ins.readFloat();
 
        this.longtd = ins.readFloat();
 
        this.altitude = ins.readFloat();
 
        this.utm_x = ins.readFloat();
 
        this.utm_y = ins.readFloat();
 
    }
 
    public gps_lcm.gps_msg copy()
    {
        gps_lcm.gps_msg outobj = new gps_lcm.gps_msg();
        outobj.time = this.time;
 
        outobj.lat = this.lat;
 
        outobj.longtd = this.longtd;
 
        outobj.altitude = this.altitude;
 
        outobj.utm_x = this.utm_x;
 
        outobj.utm_y = this.utm_y;
 
        return outobj;
    }
 
}

